/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Cidade;
import modelo.CidadeTableModel;
import remoto.ICidadeService;

/**
 *
 * @author Aluno
 */
public class CidadePrincipalTela extends javax.swing.JFrame {
    List<Cidade> cidades = new ArrayList<>();
    /**
     * Creates new form CidadePrincipal
     */
    public CidadePrincipalTela() throws NotBoundException, MalformedURLException, RemoteException {
        initComponents();
        carregaComponentes();
    }
    
    public void carregaComponentes() throws NotBoundException, MalformedURLException, RemoteException{
        ICidadeService service = (ICidadeService) Naming.lookup("rmi://localhost:1099/CidadeService");
        cidades = service.listarCidade();
        System.out.println(cidades.get(0).getNome());
        tabelaListarCidade.setModel(new CidadeTableModel(cidades));
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluirCidade = new javax.swing.JButton();
        btnInserirCidade = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarCidade = new javax.swing.JTable();
        tfBuscarCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCidade = new javax.swing.JButton();
        btnEditarCidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExcluirCidade.setText("Excluir");
        btnExcluirCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCidadeActionPerformed(evt);
            }
        });

        btnInserirCidade.setText("Inserir");
        btnInserirCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCidadeActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tabelaListarCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaListarCidade);

        tfBuscarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarCidadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar Cidade");

        btnBuscarCidade.setText("Buscar");

        btnEditarCidade.setText("Editar");
        btnEditarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInserirCidade)
                        .addGap(39, 39, 39)
                        .addComponent(btnEditarCidade)
                        .addGap(49, 49, 49)
                        .addComponent(btnExcluirCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 174, Short.MAX_VALUE))
                            .addComponent(tfBuscarCidade))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCidade)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCidade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnEditarCidade)
                    .addComponent(btnInserirCidade)
                    .addComponent(btnExcluirCidade))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCidadeActionPerformed
        // TODO add your handling code here:
        try {
           ICidadeService service = (ICidadeService) Naming.lookup("rmi://localhost:1099/CidadeService");
            service.removerCidade(cidades.get(tabelaListarCidade.getSelectedRow()));
            JOptionPane.showMessageDialog(null,"Excluido com muito suor@@");
            carregaComponentes();
        } catch (RemoteException ex) {
            Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnExcluirCidadeActionPerformed

    private void btnInserirCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCidadeActionPerformed
        CidadeInserirTela frame = null;
        try {
            frame = new CidadeInserirTela();
        } catch (NotBoundException ex) {
            Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);        
    }//GEN-LAST:event_btnInserirCidadeActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void tfBuscarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarCidadeActionPerformed

    private void btnEditarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCidadeActionPerformed
        CidadeEditarTela frame = new CidadeEditarTela();
        dispose();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);  
    }//GEN-LAST:event_btnEditarCidadeActionPerformed

    //capturas de evento dos cliques dos botoes
    
    //inserir
    public void btnInserirCidadeEventListener(ActionListener btnInserirCidadeEventListener){
        this.btnInserirCidade.addActionListener(btnInserirCidadeEventListener);
    }
    
    //editar
    public void btnEditarCidadeEventListener(ActionListener btnEditarCidadeEventListener){
        this.btnEditarCidade.addActionListener(btnEditarCidadeEventListener);
    }
    
    //excluir
    public void btnExcluirCidadeEventListener(ActionListener btnExcluirCidadeEventListener){
        this.btnExcluirCidade.addActionListener(btnExcluirCidadeEventListener);
    }
    
    //sair
    public void btnSairEventListener(ActionListener btnSairEventListener){
        this.btnSair.addActionListener(btnSairEventListener);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CidadePrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CidadePrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CidadePrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CidadePrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CidadePrincipalTela cidadeTela = null;
                try {
                    cidadeTela = new CidadePrincipalTela();
                } catch (NotBoundException ex) {
                    Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(CidadePrincipalTela.class.getName()).log(Level.SEVERE, null, ex);
                }
                cidadeTela.setVisible(true);
                cidadeTela.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCidade;
    private javax.swing.JButton btnEditarCidade;
    private javax.swing.JButton btnExcluirCidade;
    private javax.swing.JButton btnInserirCidade;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaListarCidade;
    private javax.swing.JTextField tfBuscarCidade;
    // End of variables declaration//GEN-END:variables
}
